# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ chore/docs-deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Deps
        run: npm ci
      - name: Bootstrap
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Generate docs
        run: npm run docs

